//! Macro support for the `khan` crate.

#![warn(clippy::pedantic)]
#![allow(clippy::too_many_lines)]

#[cfg(feature = "test")]
mod attr_async_test;
mod derive_entity;
mod derive_fields;
mod func_construct_filter;
mod func_construct_update;
mod prelude;
mod utils;

fn expand<F: FnOnce(proc_macro2::TokenStream) -> syn::Result<proc_macro2::TokenStream>>(
    fun: F,
    input: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    fun(input.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

/// Derives Khan's [`Entity` trait] for a struct and generates its typed CRUD helpers.
///
/// The struct must satisfy the requirements documented by the [`Entity` trait], including having a named
/// `id` field annotated with `#[serde(rename = "_id")]`.
///
/// The derive generates a helper module named after the struct in `snake_case`. The module contains typed
/// filters and updates, a field-name enum, declared projection structs, and their associated helper macros.
///
/// ## Attributes
///
/// All options are specified inside `#[entity(...)]`.
///
/// | Name | Description | Syntax example |
/// |---|---|---|
/// | `collection` | Overrides the collection name. By default, Khan uses the entity name in `snake_case`, with a trailing `Entity` suffix removed. | `#[entity(collection = "users")]` |
/// | `projections` | Declares partial views of the entity. Khan generates one projection struct for each name and implements the relevant selection traits. | `#[entity(projections(Profile(id, name), Credentials(id, email, password)))]` |
/// | `indexes` | **Requires `meta`.** Declares typed indexes. Keys are checked against entity fields and accept `1` or `"-1"` as directions. Use `__` for an unnamed index and `options = ...` for driver options. | `#[entity(indexes(email_idx(keys(email = 1), options = IndexOptions::builder().unique(true).build())))]` |
/// | `untyped_indexes` | **Requires `meta`.** Adds arbitrary [`mongodb::IndexModel`] expressions when the typed index syntax is insufficient. | `#[entity(untyped_indexes(IndexModel::builder().keys(doc! { "email": 1 }).build()))]` |
/// | `query_validation` | **Requires `meta`.** Defines a `MongoDB` query-expression validator for the entity's collection. | `#[entity(query_validation = doc! { "$gt": [{ "$strLenCP": "$name" }, 2] })]` |
/// | `skip_schema_validation` | **Requires `schema`.** Excludes this entity from generated JSON Schema validation and removes the requirement to derive `JsonSchema`. | `#[entity(skip_schema_validation)]` |
///
/// Generated BSON field names respect `#[serde(rename = "...")]`. This applies to typed filters and updates,
/// projections, typed index keys, and the generated `entity::Fields` enum.
///
/// [`Entity` trait]: https://docs.rs/khan/latest/khan/trait.Entity.html
/// [`mongodb::IndexModel`]: https://docs.rs/mongodb/latest/mongodb/struct.IndexModel.html
#[proc_macro_derive(Entity, attributes(entity))]
pub fn entity(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    expand(derive_entity::derive_entity, input)
}

/// Generates a field-name enum for a struct without deriving [`Entity`].
///
/// Given a struct named `Address`, this macro creates an `address` module containing a public `Fields` enum.
/// Each enum variant corresponds to one named struct field. The enum implements `Display`, `From<Fields> for
/// String`, and `From<Fields> for mongodb::bson::Bson`. Field values respect `#[serde(rename = "...")]`.
///
/// This is useful for subdocument types that are embedded in an entity but are not entities themselves. Using
/// the generated enum in raw BSON queries keeps field names compiler-checked and reduces bugs caused by typos,
/// just like the `entity::Fields` enum generated by [`Entity`].
///
/// ```ignore
/// use khan::{Fields, mongodb::bson::doc};
/// use serde::{Deserialize, Serialize};
///
/// #[derive(Serialize, Deserialize, Fields)]
/// struct Address {
///     city: String,
///     #[serde(rename = "postalCode")]
///     postal_code: String,
/// }
///
/// let field = format!("address.{}", address::Fields::PostalCode);
/// let filter = doc! { field: "12345" };
/// ```
///
/// Unlike [`Entity`], `Fields` does not implement Khan's entity, selection, filter, or update traits and does
/// not generate CRUD methods, typed filters, typed updates, or projections.
///
/// [`Entity`]: https://docs.rs/khan/latest/khan/derive.Entity.html
#[proc_macro_derive(Fields, attributes(serde))]
pub fn fields(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    expand(derive_fields::derive_fields, input)
}

#[allow(non_snake_case)]
#[proc_macro]
pub fn __private__construct_filter(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    expand(func_construct_filter::func_construct_filter, input)
}

#[allow(non_snake_case)]
#[proc_macro]
pub fn __private__construct_update(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    expand(func_construct_update::func_construct_update, input)
}

#[cfg(feature = "test")]
#[proc_macro_attribute]
pub fn async_test(
    attrs: proc_macro::TokenStream,
    input: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    attr_async_test::attr_async_test(&attrs.into(), input.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}
