[package]
name = "khan"
description = "A MongoDB ODM"
version = "0.0.1"
edition = "2024"
authors = ["Kit Isaev <14875494+nikis05@users.noreply.github.com>"]
license = "MIT"

[dependencies]
dashmap = "6.1.0"
futures-util = "0.3.31"
mongodb = "3.2.3"
serde = "1.0.219"
khan-macros = { version = "0.0.1", path = "../khan-macros" }
inventory = { version = "0.3.20", optional = true }
schemars = { version = "0.8.22", optional = true }

[features]
default = ["meta", "schema"]
meta = ["dep:inventory", "khan-macros/meta"]
schema = ["meta", "dep:schemars", "khan-macros/schema"]

[dev-dependencies]
testcontainers = { version = "0.23.3", features = ["reusable-containers"] }
ctor = "0.4.1"
fakeit = "1.3.0"
testcontainers-modules = { version = "0.11.6", features = ["mongo"] }
tokio = { version = "1.44.2", features = ["rt", "macros"] }
khan-macros = { version = "0.0.1", path = "../khan-macros", features = [
    "test",
] }
