[package]
name = "khan"
description = "A MongoDB ODM"
keywords = ["mongodb", "odm", "orm", "database", "bson"]
categories = ["database"]
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
dashmap = "6.1.0"
futures-util = "0.3.31"
mongodb = "3.7.0"
serde = "1.0.219"
khan-macros = { version = "=0.1.1", path = "../khan-macros" }
inventory = { version = "0.3.20", optional = true }
schemars = { version = "0.8.22", optional = true }
indexmap = "2.14.0"

[features]
meta = ["dep:inventory", "khan-macros/meta"]
schema = ["meta", "dep:schemars", "khan-macros/schema"]
guides = []

[dev-dependencies]
ctor = "0.4.1"
fakeit = "1.3.0"
tokio = { version = "1.44.2", features = ["rt", "macros"] }
khan-macros = { version = "=0.1.1", path = "../khan-macros", features = [
    "test",
] }
