[package]
name = "khan-macros"
description = "Macros for Khan crate"
version = "0.0.1"
edition = "2024"
authors = ["Kit Isaev <14875494+nikis05@users.noreply.github.com>"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
darling = "0.23.0"
either = "1.16.0"
heck = "0.5.0"
indexmap = { version = "2.14.0", optional = true }
itertools = "0.15.0"
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.106"
quote = "1.0.46"
syn = "2.0.118"

[features]
meta = ["dep:indexmap"]
schema = []
test = []
