[package]
name = "khan-macros"
description = "Macros for Khan crate"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true

[lib]
proc-macro = true

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
darling = "0.23.0"
either = "1.16.0"
heck = "0.5.0"
indexmap = { version = "2.14.0", optional = true }
itertools = "0.15.0"
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.106"
quote = "1.0.46"
syn = "2.0.118"

[features]
meta = ["dep:indexmap"]
schema = []
test = []
